// <auto-generated />
using CourseProject.DAL.EF_Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseProject.DAL.Migrations
{
    [DbContext(typeof(DB_Configuration))]
    partial class DB_ConfigurationModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("CourseProject.DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Algebra",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quantum Mechanics",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Organic Chemistry",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Genetics",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "World History",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "English Literature",
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "C# Programming",
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "Logic and Reasoning",
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cartography",
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "Painting Techniques",
                            TeacherId = 10
                        });
                });

            modelBuilder.Entity("CourseProject.DAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Roe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lucy Hale"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Peter Parker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mary Jane"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bruce Wayne"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Clark Kent"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Diana Prince"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Barry Allen"
                        });
                });

            modelBuilder.Entity("CourseProject.DAL.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Johnson",
                            Speciality = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Smith",
                            Speciality = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clara James",
                            Speciality = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "David Brown",
                            Speciality = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emma Wilson",
                            Speciality = "History"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Frank Taylor",
                            Speciality = "Literature"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Grace Thomas",
                            Speciality = "Programming"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Henry Lee",
                            Speciality = "Philosophy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ivy Adams",
                            Speciality = "Geography"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jack White",
                            Speciality = "Art"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("Student_Cource", (string)null);
                });

            modelBuilder.Entity("CourseProject.DAL.Models.Course", b =>
                {
                    b.HasOne("CourseProject.DAL.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("CourseProject.DAL.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseProject.DAL.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseProject.DAL.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
